# -*- coding: utf-8 -*-
"""GMM_L9_GHK2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15dmhzBF-ZPeV2Wez8RJXVchAujGBgaAt
"""

# ==============================================================================
# HỆ THỐNG TÍNH Z-SCORE VÀ VẼ ĐỒ THỊ BƯỚC NHẢY 0.5 ĐIỂM HOÀN CHỈNH
# ==============================================================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.mixture import GaussianMixture
from scipy.stats import norm
from google.colab import files
import io

print("--- BẮT ĐẦU XỬ LÝ ĐIỂM GIỮA KỲ ---")

# 1. Tải file Excel
uploaded = files.upload()
file_name = list(uploaded.keys())[0]
df = pd.read_excel(io.BytesIO(uploaded[file_name]), header=0) # Đọc dòng đầu tiên của Excel làm header, chứa GK

# 2. Xác định cột điểm Giữa kỳ
col_diem = 'CK'  # Đổi tên này nếu file Excel ghi khác

# 3. Làm sạch dữ liệu và tạo df_clean
df_clean = df.dropna(subset=[col_diem]).copy()
X = df_clean[[col_diem]].values

# 4. Tính Z-score truyền thống (Đơn đỉnh)
mu_gk = df_clean[col_diem].mean()
sigma_gk = df_clean[col_diem].std()
df_clean['Z_DonDinh_TruyenThong'] = (df_clean[col_diem] - mu_gk) / sigma_gk

# 5. Huấn luyện GMM và tính Z-score hiệu chỉnh (Đa đỉnh)
gmm = GaussianMixture(n_components=2, random_state=42)
gmm.fit(X)

means = gmm.means_.flatten()
stds = np.sqrt(gmm.covariances_).flatten()
weights = gmm.weights_.flatten()

idx_sort = np.argsort(means)
mu1, sigma1, pi1 = means[idx_sort[0]], stds[idx_sort[0]], weights[idx_sort[0]]
mu2, sigma2, pi2 = means[idx_sort[1]], stds[idx_sort[1]], weights[idx_sort[1]]

f1 = norm.pdf(df_clean[col_diem], loc=mu1, scale=sigma1)
f2 = norm.pdf(df_clean[col_diem], loc=mu2, scale=sigma2)

gamma1 = (pi1 * f1) / (pi1 * f1 + pi2 * f2)
gamma2 = 1.0 - gamma1

z_cum1 = (df_clean[col_diem] - mu1) / sigma1
z_cum2 = (df_clean[col_diem] - mu2) / sigma2

df_clean['GK_XacSuat_Cum1'] = np.round(gamma1, 4)
df_clean['GK_XacSuat_Cum2'] = np.round(gamma2, 4)
df_clean['Z_DaDinh_GMM'] = np.round(gamma1 * z_cum1 + gamma2 * z_cum2, 4)

# 6. HIỂN THỊ ĐỒ THỊ TÍCH HỢP BƯỚC NHẢY 0.5 ĐIỂM
plt.figure(figsize=(12, 6))

sns.histplot(
    df_clean[col_diem],
    binwidth=0.5,             # Độ rộng mỗi cột = 0.5 điểm
    binrange=(0, 10),          # Dải điểm từ 0 đến 10
    stat="density",
    color='skyblue',
    edgecolor='black',
    alpha=0.6,
    label='Phổ điểm thực tế'
)

x_axis = np.linspace(0, 10, 500)
plt.plot(x_axis, pi1 * norm.pdf(x_axis, mu1, sigma1), 'r--', linewidth=2, label=f'Cụm Đại Trà (μ={mu1:.1f})')
plt.plot(x_axis, pi2 * norm.pdf(x_axis, mu2, sigma2), 'g--', linewidth=2, label=f'Cụm Tăng Cường (μ={mu2:.1f})')
plt.plot(x_axis, pi1 * norm.pdf(x_axis, mu1, sigma1) + pi2 * norm.pdf(x_axis, mu2, sigma2), 'b-', linewidth=2.5, label='Tổng hợp GMM 2 đỉnh')

plt.title('PHÂN TÍCH PHỔ ĐIỂM GIỮA KỲ BẰNG MÔ HÌNH GMM (BƯỚC NHẢY 0.5 ĐIỂM)', fontsize=13, fontweight='bold')
plt.xlabel('Điểm số giữa kỳ', fontsize=11)
plt.ylabel('Mật độ xác suất', fontsize=11)
plt.xticks(np.arange(0, 10.5, 0.5), rotation=45)
plt.xlim(0, 10)
plt.legend(fontsize=10)
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# 7. Xuất file kết quả
output_filename = "Ket_Qua_ZScore_GiuaKy.xlsx"
df_clean.to_excel(output_filename, index=False)
files.download(output_filename)